
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fred
 */
public class PanelSynthese extends javax.swing.JPanel {

    /**
     * Creates new form patientsJPanel
     */
    public PanelSynthese () {
        initComponents();
        jTextRG.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setOpaque(false);
        //jTabbedPane.setSelectedIndex(0);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextRG = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextMOC = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextCS = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTitle.setForeground(new java.awt.Color(102, 102, 102));
        jTitle.setText("Synthèse :");

        jTabbedPane.setToolTipText("Synthèses");
        jTabbedPane.setPreferredSize(new java.awt.Dimension(395, 500));

        jTextRG.setEditable(false);
        jTextRG.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jTextRG.setContentType("text/html"); // NOI18N
        jTextRG.setOpaque(false);
        jScrollPane1.setViewportView(jTextRG);

        jTabbedPane.addTab("Mémoire VS", jScrollPane1);

        jTextMOC.setEditable(false);
        jTextMOC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextMOC.setOpaque(false);
        jScrollPane2.setViewportView(jTextMOC);

        jTabbedPane.addTab("Rotation", jScrollPane2);

        jTextCS.setEditable(false);
        jTextCS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextCS.setOpaque(false);
        jScrollPane3.setViewportView(jTextCS);

        jTabbedPane.addTab("Discrimination", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTitle)
                            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTabbedPane jTabbedPane;
    public static javax.swing.JTextPane jTextCS;
    public static javax.swing.JTextPane jTextMOC;
    public static javax.swing.JTextPane jTextRG;
    public static javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables
}
